export const LAYOUT = "LAYOUT";
export const NAVIGATION_MENU = "NAVIGATION_MENU";
export const NAMESPACE_APPLICATION = "APPLICATION";
export const SET_FLOATING = NAMESPACE_APPLICATION + "/SET_FLOATING";
export const SET_MINI_DRAWER_MENU =
  NAMESPACE_APPLICATION + "/SET_MINI_DRAWER_MENU";
export const SET_FOOTER_INSET = NAMESPACE_APPLICATION + "/SET_FOOTER_INSET";
export const SET_TYPE_TOOLBAR = NAMESPACE_APPLICATION + "/SET_TYPE_TOOLBAR";
export const SET_DARKMODE = NAMESPACE_APPLICATION + "/SET_DARKMODE";
export const SET_CLIPPED_TOOLBAR =
  NAMESPACE_APPLICATION + "/SET_CLIPPED_TOOLBAR";
export const SAVE_SETTINGS = NAMESPACE_APPLICATION + "/SAVE_SETTINGS";
export const SET_NAVIGATION_MENU =
  NAMESPACE_APPLICATION + "/SET_NAVIGATION_MENU";
