export const SETTINGS_LOAD_START = "SETTINGS_LOAD_START";
export const SETTINGS_LOAD_END = "SETTINGS_LOAD_END";
export const SETTINGS_SET_DARK_MODE = "SETTINGS_SET_DARK_MODE";
export const SETTINGS_SET_CLIPPED_TOOLBAR = "SETTINGS_SET_CLIPPED_TOOLBAR";
export const SETTINGS_SET_TYPE = "SETTINGS_SET_TYPE";
export const SETTINGS_SET_FOOTER_INSET = "SETTINGS_SET_FOOTER_INSET";
export const SETTINGS_SET_MINI_DRAWER_MENU = "SETTINGS_SET_MINI_DRAWER_MENU";
export const SETTINGS_SET_FLOATING = "SETTINGS_SET_FLOATING";
