export const APPLICATION_LOAD_START = "APPLICATION_LOAD_START";
export const APPLICATION_LOAD_END = "APPLICATION_LOAD_END";
export const APPLICATION_SET_DARK_MODE = "APPLICATION_SET_DARK_MODE";
export const APPLICATION_SET_CLIPPED_TOOLBAR =
  "APPLICATION_SET_CLIPPED_TOOLBAR";
export const APPLICATION_SET_TYPE = "APPLICATION_SET_TYPE";
export const APPLICATION_SET_FOOTER_INSET = "APPLICATION_SET_FOOTER_INSET";
export const APPLICATION_SET_MINI_DRAWER_MENU =
  "APPLICATION_SET_MINI_DRAWER_MENU";
export const APPLICATION_SET_FLOATING = "APPLICATION_SET_FLOATING";
export const APPLICATION_SET_NAVIGATION_MENU =
  "APPLICATION_SET_NAVIGATION_MENU";
